C THE EKEPL PROCEDURE
C Gooding & Odell (1985) procedure for solving Kepler Equation.

       DOUBLE PRECISION FUNCTION EKEPL(EM, E1)
C       KEPLER'S EQUATION, EM = EKEPL - (1 - E1) *DSIN(EKEPL),
C       WITH E1 IN RANGE 1 TO 0 INCLUSIVE, SOLVED ACCURATELY
C       (BASED ON EKEPL3, BUT ENTERING E1 NOT E)
       IMPLICIT DOUBLE PRECISION (A-H,O-2Z)

       PARAMETER (PI=3.14159265358979323846264338328D0, TWOPI=2D0*PI,

     1 PINEG=-PI, SW=0.25D0, AHALF=0.5D0, ATHIRD=AHALF/1.5D0)
C1      RANGE-REDUCE EM TO LIE IN RANGE -PI TO PI

       EMR = DMOD(EM, TWOPT)
       IF (EMR.LT.PINEG) EMR = EMR + TWOPI
       IF (EMR.GT.PI) EMR = EMR - TWOPI
       EE = EMR
       IF (EE) 1,4,2
     1 EE = -EE

C       (EMR IS RANGE-REDUCED EM & EE IS ABSOLUTE VALUE OF EMR)
C2      STARTER BY FIRST SOLVING CUBIC EQUATION
     2 E = 1D0 - E1
       W = DCBSOL(E, 2D0*E1, 3D0*EE)
C       EFFECTIVELY INTERPOLATE IN EMR (ABSOLUTE VALUE)
       EE = (EE*EE + (PI - EE) *W)/PI
       IF (EMR.LT.ODO) EE = -EE
C       DO TWO ITERATIONS OF HALLEY, EACH FOLLOWED BY NEWTON

       DO 3 ITER=1,2
       FDD = E*DSIN(EE)
       FDDD = E*DCOS (EE)
       IF (EE*EE/6D0 + E1 .GE. SW) THEN
        F = (EE - FDD) - EMR
        FD = 1D0 - FDDD
       ELSE
        F = EMKEP(E1,EE) - EMR
        FD = 2D0*E*DSIN(AHALF*EE) **2 + E1
       END IF
       DEE = F*FD/(AHALF*F*FDD - FD*FD)
       F = F + DEE*(FD + AHALF*DEE*(FDD + ATHIRD*DEE*FDDD) )
C*       TO REDUCE THE DANGER OF UNDERFLOW REPLACE THE LAST LINE BY
C*     W = FD + AHALF*DEE*(FDD + ATHIRD*DEE*FDDD)

       FD = FD + DEE*(FDD + AHALF*DEE*FDDD)
     3 EE = EE + DEE - F/FD

C*      IF REPLACING AS ABOVE, THEN ALSO REPLACE THE LAST LINE BY
C*   3 EE = EE - (F - DEE*(FD - W))/FD

C5      RANGE-EXPAND
     4 EKEPL = EE + (EM - EMR)
       RETURN
       END
